workflows:
    android-workflow-id:
        name: Android Sample Workflow
        # .......    
        # .......
        # .......  
    ios-workflow-id:
        name: iOS Sample Workflow
        # ......
artifacts:
        - myexpoapp/app/build/**/outputs/**/*.apk
